CREATE TABLE TIN_TIPOS_NUTRIENTES
(
	TIN_TIPOS_NUTRIENTES_ID INT(6) NOT NULL,
	TIN_NOME VARCHAR(35) NOT NULL,
	PRIMARY KEY (TIN_TIPOS_NUTRIENTES_ID)
);

CREATE TABLE NUT_NUTRIENTES
(
	NUT_NUTRIENTES_ID INT(6) NOT NULL,
	NUT_NOME VARCHAR(35) NOT NULL,
	NUT_TIN_TIPOS_NUTRIENTES_ID INT(6),
	PRIMARY KEY (NUT_NUTRIENTES_ID),
	FOREIGN KEY (NUT_TIN_TIPOS_NUTRIENTES_ID) REFERENCES TIN_TIPOS_NUTRIENTES(TIN_TIPOS_NUTRIENTES_ID)
);

CREATE TABLE GRA_GRUPOS_ALIMENTARES
(
	GRA_GRUPOS_ALIMENTARES_ID INT(6) NOT NULL,
	GRA_NOME VARCHAR(35) NOT NULL,
	PRIMARY KEY (GRA_GRUPOS_ALIMENTARES_ID)
);

CREATE TABLE ALI_ALIMENTOS
(
	ALI_ALIMENTOS_ID INT(6) NOT NULL,
	ALI_NOME VARCHAR(35) NOT NULL,
	ALI_INDICE_GLICEMICO CHAR(1) NOT NULL,
	ALI_PORCAO_GRAMAS DECIMAL(5,2),
	ALI_GRA_GRUPOS_ALIMENTARES_ID INT(6),
	PRIMARY KEY (ALI_ALIMENTOS_ID),
	FOREIGN KEY (ALI_GRA_GRUPOS_ALIMENTARES_ID) REFERENCES GRA_GRUPOS_ALIMENTARES(GRA_GRUPOS_ALIMENTARES_ID),
	CHECK (ALI_INDICE_GLICEMICO='A' OR ALI_INDICE_GLICEMICO='M' OR ALI_INDICE_GLICEMICO='B')
);

CREATE TABLE VAN_VALORES_NUTRICIONAIS
(
	VAN_ALI_ALIMENTOS_ID INT(6) NOT NULL,
	VAN_NUT_NUTRIENTES_ID INT(6) NOT NULL,
	VAN_QUANTIDADE VARCHAR(10) NOT NULL,
	PRIMARY KEY (VAN_ALI_ALIMENTOS_ID, VAN_NUT_NUTRIENTES_ID),
	FOREIGN KEY (VAN_ALI_ALIMENTOS_ID) REFERENCES ALI_ALIMENTOS(ALI_ALIMENTOS_ID),
	FOREIGN KEY (VAN_NUT_NUTRIENTES_ID) REFERENCES NUT_NUTRIENTES(NUT_NUTRIENTES_ID)
);

CREATE TABLE TIR_TIPOS_REFEICOES
(
	TIR_TIPOS_REFEICOES_ID INT(6) NOT NULL,
	TIR_NOME VARCHAR(35) NOT NULL,
	PRIMARY KEY (TIF_TIPOS_REFEICOES_ID)
);

CREATE TABLE REF_REFEICOES
(
	REF_REFEICOES_ID INT(6) NOT NULL,
	REF_NOME VARCHAR(35) NOT NULL,
	REF_TIR_TIPOS_REFEICOES_ID INT(6),
	PRIMARY KEY (REF_REFEICOES_ID),
	FOREIGN KEY (REF_TIR_TIPOS_REFEICOES_ID) REFERENCES TIR_TIPOS_REFEICOES(TIR_TIPOS_REFEICOES_ID)
);

CREATE TABLE USU_USUARIOS
(
	USU_USUARIOS_ID INT(6) NOT NULL,
	USU_NOME VARCHAR(50) NOT NULL,
	USU_LOGIN VARCHAR(35),
	USU_SENHA VARCHAR(35),
	USU_EMAIL VARCHAR(50),
	PRIMARY KEY (USU_USUARIOS_ID)
);

CREATE TABLE DIE_DIETAS
(
	DIE_DIETAS_ID INT(6) NOT NULL,
	DIE_NOME VARCHAR(35) NOT NULL,
	DIE_STATUS CHAR(1) NOT NULL,
	DIE_USU_USUARIOS_ID INT(6),
	PRIMARY KEY (DIE_DIETAS_ID),
	FOREIGN KEY (DIE_USU_USUARIOS_ID) REFERENCES USU_USUARIOS(USU_USUARIOS_ID),
	CHECK (DIE_STATUS='A' OR DIE_STATUS='D')
);

CREATE TABLE RRD_RELACAO_REFEICOES_DIETAS
(
	RRD_DIE_DIETAS_ID INT(6) NOT NULL,
	RRD_REF_REFEICOES_ID INT(6) NOT NULL,
	PRIMARY KEY (RRD_DIE_DIETAS_ID, RRD_REF_REFEICOES_ID)
	FOREIGN KEY (RRD_DIE_DIETAS_ID) REFERENCES DIE_DIETAS(DIE_DIETAS_ID),
	FOREIGN KEY (RRD_REF_REFEICOES_ID) REFERENCES REF_REFEICOES(REF_REFEICOES_ID)
);